---
- name: Site
  hosts: all
  become: yes
  become_user: root
  handlers:
    - name: reload systemd
      systemd: daemon_reload=yes
  roles:
    - role: hifis.unattended_upgrades
      vars:
        unattended_automatic_reboot: true
    - role: sansible.ssmtp
      vars:
        sansible_ssmtp_group: ssmtp
        sansible_ssmtp_user: ssmtp
        sansible_ssmtp_mailserver_username: "{{ secret_ssmtp_auth_user }}"
        sansible_ssmtp_mailserver_password: "{{ secret_ssmtp_auth_pass }}"
        sansible_ssmtp_mailserver_host: smtp.gmail.com
        sansible_ssmtp_mailserver_port: "587"
    - home-assistant
  tasks:
    - name: enable runtime watchdog
      lineinfile:
        line: RuntimeWatchdogSec=15
        regexp: RuntimeWatchdogSec=
        path: /etc/systemd/system.conf
        state: present
      notify: reload systemd

    - name: enable reboot watchdog
      lineinfile:
        line: RebootWatchdogSec=10min
        regexp: RebootWatchdogSec=
        path: /etc/systemd/system.conf
        state: present
      notify: reload systemd
