---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: focal
    image: ubuntu:focal
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
