---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: focal
    image: ubuntu:focal
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
verifier:
  name: ansible
